[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm run docker-start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
