# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "032e75d7a920d85176feab7fda8524c8"
name = "Afflow"
application_url = "https://www.afflow.in"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app_subscriptions/update"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_app_proxy,write_discounts"

[auth]
redirect_urls = [
  "https://www.afflow.in/auth/callback",
  "https://www.afflow.in/auth/shopify/callback",
  "https://www.afflow.in/api/auth/callback"
]

[app_proxy]
url = "https://www.afflow.in/proxy"
subpath = "ref"
prefix = "a"
